// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7NQ5hAmOdMgKYEiwilDLXiKw7U_z49uI',
    appId: '1:391299946628:android:8efa2fbb6a03d13dc3cad1',
    messagingSenderId: '391299946628',
    projectId: 'betapp-baf8c',
    databaseURL: 'https://betapp-baf8c-default-rtdb.firebaseio.com',
    storageBucket: 'betapp-baf8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAViIvCmifN865dZN2k4JUJTKjBb6ahcBU',
    appId: '1:391299946628:ios:4298d19f2b78fecbc3cad1',
    messagingSenderId: '391299946628',
    projectId: 'betapp-baf8c',
    databaseURL: 'https://betapp-baf8c-default-rtdb.firebaseio.com',
    storageBucket: 'betapp-baf8c.appspot.com',
    iosClientId: '391299946628-9o4amvuiojo7qpiqic8n4qoc3ravja42.apps.googleusercontent.com',
    iosBundleId: 'com.dailyrolloverproApp.dailyRolloverProapp',
  );
}
